#!/usr/bin/env bash
# system.sh — timezone, locale, hostname, keymap, fstab, users, finalization
source "${LIB_DIR}/protection.sh"

# --- Timezone ---

system_set_timezone() {
    local tz="${TIMEZONE:-UTC}"
    einfo "Setting timezone: ${tz}"

    try "Setting timezone" \
        chroot_exec "ln -sf /usr/share/zoneinfo/${tz} /etc/localtime"

    # Hardware clock (UTC by default, localtime for dual-boot with Windows)
    if [[ "${WINDOWS_DETECTED:-0}" == "1" ]]; then
        chroot_exec "echo localtime > /etc/hwclock" || true
        ewarn "Hardware clock set to localtime for Windows dual-boot"
    fi
}

# --- Hostname ---

system_set_hostname() {
    local hostname="${HOSTNAME:-chimera}"

    # Validate hostname (RFC 1123)
    if [[ ! "${hostname}" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$ ]]; then
        ewarn "Invalid hostname '${hostname}', falling back to 'chimera'"
        hostname="chimera"
    fi

    einfo "Setting hostname: ${hostname}"

    chroot_exec "echo '${hostname}' > /etc/hostname"

    # Update /etc/hosts
    chroot_exec "cat > /etc/hosts << HOSTSEOF
# /etc/hosts
127.0.0.1   localhost
::1         localhost
127.0.1.1   ${hostname}.localdomain ${hostname}
HOSTSEOF"
}

# --- Keymap ---

system_set_keymap() {
    local keymap="${KEYMAP:-us}"
    einfo "Setting keymap: ${keymap}"

    # Chimera uses console-setup from Debian
    chroot_exec "mkdir -p /etc/default"
    chroot_exec "cat > /etc/default/keyboard << 'KBEOF'
XKBMODEL=\"pc105\"
XKBLAYOUT=\"${keymap}\"
XKBVARIANT=\"\"
XKBOPTIONS=\"\"
KBEOF"
}

# --- fstab ---

generate_fstab() {
    einfo "Generating /etc/fstab..."

    if [[ "${DRY_RUN}" == "1" ]]; then
        einfo "[DRY-RUN] Would generate fstab"
        return 0
    fi

    # Use genfstab if available (Chimera provides this)
    if command -v genfstab &>/dev/null; then
        try "Generating fstab with genfstab" bash -c \
            "genfstab -U '${MOUNTPOINT}' >> '${MOUNTPOINT}/etc/fstab'"
    else
        # Manual fstab generation
        _generate_fstab_manual
    fi

    einfo "fstab generated"
}

# --- crypttab ---

generate_crypttab() {
    if [[ "${LUKS_ENABLED:-no}" != "yes" ]]; then
        return 0
    fi

    einfo "Generating /etc/crypttab..."

    local luks_uuid
    luks_uuid=$(get_uuid "${LUKS_PARTITION}")

    if [[ -z "${luks_uuid}" ]]; then
        eerror "Cannot determine UUID for LUKS partition ${LUKS_PARTITION}"
        return 1
    fi

    echo "cryptroot UUID=${luks_uuid} none luks" > "${MOUNTPOINT}/etc/crypttab"

    einfo "crypttab generated for ${LUKS_PARTITION} (UUID=${luks_uuid})"
}

_generate_fstab_manual() {
    local fstab="${MOUNTPOINT}/etc/fstab"
    local fs="${FILESYSTEM:-ext4}"

    {
        echo "# /etc/fstab"
        echo "# Generated by ${INSTALLER_NAME} v${INSTALLER_VERSION}"
        echo "#"
        echo "# <fs>                                  <mountpoint>  <type>  <opts>                                  <dump/pass>"

        # Root filesystem
        local root_dev="${ROOT_PARTITION}"
        if [[ "${LUKS_ENABLED:-no}" == "yes" ]]; then
            root_dev="/dev/mapper/cryptroot"
        fi
        local root_uuid
        root_uuid=$(get_uuid "${root_dev}")

        if [[ -n "${root_uuid}" ]]; then
            case "${fs}" in
                btrfs)
                    echo "UUID=${root_uuid}   /             btrfs   subvol=@,compress=zstd,noatime,defaults  0 1"
                    if [[ -n "${BTRFS_SUBVOLUMES:-}" ]]; then
                        local IFS=':'
                        local -a parts
                        read -ra parts <<< "${BTRFS_SUBVOLUMES}"
                        local idx
                        for (( idx = 0; idx < ${#parts[@]}; idx += 2 )); do
                            local subvol="${parts[$idx]}"
                            local mpoint="${parts[$((idx + 1))]}"
                            [[ "${subvol}" == "@" ]] && continue
                            echo "UUID=${root_uuid}   ${mpoint}          btrfs   subvol=${subvol},compress=zstd,noatime,defaults  0 2"
                        done
                    fi
                    ;;
                ext4)
                    echo "UUID=${root_uuid}   /             ext4    noatime,defaults        0 1"
                    ;;
                xfs)
                    echo "UUID=${root_uuid}   /             xfs     noatime,defaults        0 1"
                    ;;
            esac
        else
            echo "${root_dev}              /             ${fs}     noatime,defaults        0 1"
        fi

        # ESP
        local esp_uuid
        esp_uuid=$(get_uuid "${ESP_PARTITION}")
        local esp_mount="/boot/efi"
        [[ "${BOOTLOADER_TYPE:-grub}" == "systemd-boot" ]] && esp_mount="/boot"

        if [[ -n "${esp_uuid}" ]]; then
            echo "UUID=${esp_uuid}   ${esp_mount}          vfat    noatime,defaults        0 2"
        else
            echo "${ESP_PARTITION}              ${esp_mount}          vfat    noatime,defaults        0 2"
        fi

        # Swap partition
        if [[ "${SWAP_TYPE:-}" == "partition" && -n "${SWAP_PARTITION:-}" ]]; then
            local swap_uuid
            swap_uuid=$(get_uuid "${SWAP_PARTITION}")
            if [[ -n "${swap_uuid}" ]]; then
                echo "UUID=${swap_uuid}   none          swap    sw              0 0"
            else
                echo "${SWAP_PARTITION}              none          swap    sw              0 0"
            fi
        fi

        echo "tmpfs                                   /tmp          tmpfs   defaults,nosuid,nodev   0 0"

    } > "${fstab}"
}

# --- Kernel ---

kernel_install() {
    local kernel_type="${KERNEL_TYPE:-lts}"
    einfo "Installing kernel: linux-${kernel_type}"

    case "${kernel_type}" in
        lts)
            apk_install "Installing LTS kernel" linux-lts
            ;;
        stable)
            apk_install "Installing stable kernel" linux-stable
            ;;
    esac

    # Install firmware meta-package (pulls in hardware-specific firmware subpackages)
    apk_install "Installing firmware" firmware-linux-meta

    # CPU microcode
    local ucode_pkg
    ucode_pkg=$(get_microcode_package "${CPU_VENDOR:-}")
    if [[ -n "${ucode_pkg}" ]]; then
        apk_install "Installing CPU microcode" "${ucode_pkg}"
    fi

    # Generate initramfs
    try "Generating initramfs" \
        chroot_exec "update-initramfs -c -k all"

    einfo "Kernel installed"
}

# --- Networking ---

install_networking() {
    einfo "Installing networking..."

    apk_install "Installing NetworkManager" networkmanager

    # Enable NetworkManager via dinit
    try "Enabling NetworkManager" \
        chroot_exec "dinitctl -o enable networkmanager"

    einfo "Networking configured"
}

# --- Users ---

system_create_users() {
    einfo "Creating users..."

    # Set root password (chpasswd -e avoids exposing hash in process list)
    if [[ -n "${ROOT_PASSWORD_HASH:-}" ]]; then
        try "Setting root password" \
            chroot_exec "echo 'root:${ROOT_PASSWORD_HASH}' | chpasswd -e"
    fi

    # Create regular user
    if [[ -n "${USERNAME:-}" ]]; then
        local groups="${USER_GROUPS:-wheel,audio,video,input,plugdev}"

        # Filter out groups that don't exist on the target system
        local valid_groups=""
        local g
        IFS=',' read -ra _groups <<< "${groups}"
        for g in "${_groups[@]}"; do
            if chroot_exec "getent group ${g}" &>/dev/null; then
                valid_groups+="${valid_groups:+,}${g}"
            else
                ewarn "Group '${g}' does not exist, skipping"
            fi
        done
        groups="${valid_groups:-wheel}"

        try "Creating user ${USERNAME}" \
            chroot_exec "useradd -m -G ${groups} -s /bin/bash ${USERNAME}"

        if [[ -n "${USER_PASSWORD_HASH:-}" ]]; then
            try "Setting user password" \
                chroot_exec "echo '${USERNAME}:${USER_PASSWORD_HASH}' | chpasswd -e"
        fi

        # Setup doas (Chimera uses doas instead of sudo by default)
        chroot_exec "mkdir -p /etc"
        chroot_exec "echo 'permit persist :wheel' > /etc/doas.conf"
        chroot_exec "chmod 0400 /etc/doas.conf"

        einfo "User ${USERNAME} created with groups: ${groups}"
    fi

    # SSH
    if [[ "${ENABLE_SSH:-no}" == "yes" ]]; then
        apk_install "Installing OpenSSH" openssh

        try "Enabling sshd" \
            chroot_exec "dinitctl -o enable sshd"

        einfo "SSH server enabled"
    fi
}

# --- Finalization ---

system_finalize() {
    einfo "Finalizing system..."

    # Enable syslog
    try "Enabling syslog" \
        chroot_exec "dinitctl -o enable syslog-ng" 2>/dev/null || true

    # Generate machine-id
    chroot_exec "dbus-uuidgen --ensure=/etc/machine-id" 2>/dev/null || true

    # Set correct date/time inside chroot if possible
    chroot_exec "hwclock --systohc" 2>/dev/null || true

    # Clean up installer artifacts from target disk
    rm -rf "${MOUNTPOINT}${CHECKPOINT_DIR_SUFFIX}" 2>/dev/null || true
    rm -f "${MOUNTPOINT}/tmp/$(basename "${CONFIG_FILE}")" 2>/dev/null || true

    einfo "System finalization complete"
}
